# Generated by Django 5.0.6 on 2024-07-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0002_rental_created_at_rental_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentaltype",
            name="limit",
            field=models.PositiveIntegerField(default="10"),
        ),
    ]
